name: Centos 7 CI

on:
  push:
    branches:
      - main
      - feature/*
      - features/*
      - fix/*
jobs:

  build:

    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        buildtype: [Release,Debug]
        build_name: [all,solver,solver-no-ortools]
        include:
          - build_name: all
            system_build: ON
            build_ortools: ON
          - build_name: solver
            system_build: OFF
            build_ortools: ON
          - build_name: solver-no-ortools
            system_build: OFF
            build_ortools: OFF
            
    runs-on: ubuntu-latest
    container: 'centos:7'

    steps:
    - uses: actions/checkout@v2

    - name: Install libraries
      run: |
           yum update -y
           yum install -y git epel-release redhat-lsb-core autoconf automake libtool gtk2-devel gcc gcc-c++ make centos-release-scl scl-utils
           yum install -y cmake3 devtoolset-7

    - name: Configure and build
      run: |
           source /opt/rh/devtoolset-7/enable
           cmake3 -B _build -S . -DBUILD_ortools=${{ matrix.build_ortools }} -DBUILD_not_system=ON -DBUILD_system=${{ matrix.system_build }} -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} -DDEPS_INSTALL_DIR=rte-antares-deps-${{ matrix.buildtype }}

    - name: Archive upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-deps-centos7-${{ matrix.buildtype }}-${{ matrix.build_name }}
        path: |
          rte-antares-deps-${{ matrix.buildtype }}
