name: Release asset upload (Linux)

on:
  release:
    types: [created]

env:
  GITHUB_TOKEN: ${{ github.token }}
  
jobs:

  windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        buildtype: [Release,Debug]

    steps:
    - uses: actions/checkout@v2 
    
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.0

    - name: Configure and build
      run: |
           cmake -B _build -S . -DBUILD_sirius=ON -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} -DDEPS_INSTALL_DIR=rte-antares-deps-${{ matrix.buildtype }}
           
    - name: Create archive
      run: |
           tar cvf  rte-antares-deps-${{ matrix.os }}-${{ matrix.buildtype }}.tar.gz rte-antares-deps-${{ matrix.buildtype }}
           
    - name: Upload .deb
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: rte-antares-deps-${{ matrix.os }}-${{ matrix.buildtype }}.tar.gz
        asset_name: rte-antares-deps-${{ matrix.os }}-${{ matrix.buildtype }}.tar.gz
        asset_content_type: application/gzip