name: Windows CI (VCPKG)

on:
  push:
    branches:
      - main
      - feature/init
jobs:

  windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        buildtype: [Release,Debug]

    steps:
    - uses: actions/checkout@v2
        
    - name: Configure and build
      run: |
           cmake -B _build -S . -DBUILD_sirius=ON -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }}
    
    - name: Archive creation
      run: |
           cd _build
           cpack -G ZIP

    - name: Archive upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-deps-${{ matrix.os }}-${{ matrix.buildtype }}
        path: _build/rte-antares-deps-*.zip
